### ISSUE TITLE
DEV-37: Do not hide icon in the progress bar

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/MERN-ChatBot#62]
At the moment the progress bar is implemented in the way that it hides the image when the user does not hover on it and shows when the mouse is over the progress bar:

![sm2](https://user-images.githubusercontent.com/26466644/66269244-949a3680-e846-11e9-88df-09e756e9ee51.gif)

Because of this, the width of the progress bar changes and it generates a strange effect as if the progress of uncovering of the info decreases. Some users complained about this.

Also, I think, not everyone hovers on the progress and they do not see the pictures which are created to motivate users to uncover the info of the page. So, probably, if I do not hide the image at all, I improve 2 things: width does not change and the image is always visible motivating people to uncover more info.

To work on this issue, please use a branch **DEV-37** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**IMPORTANT!** Before creating a PR be sure that all the tests are passing and the coverage is 100%. And also do not forget to update the documentation in Storybooks and Styleguidist.

**Comment by TetianaKlymchuk** [comment]
Hi! I can help with this task! :)

**Comment by KovDimaY** [comment]
Yes, sure, I am assigning it to you! Do not hesitate to ask question if you need some help! :)

**Comment by KovDimaY** [comment]
Perfect job, @TetianaKlymchuk! I have just approved and merged your PR! Thank you for your contribution! ❤️
