### ISSUE TITLE
DEV-38: Add new certification to the Education Page

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/MERN-ChatBot#64]
I have just finished another course on Udemy so I would like to add it to the project.

The certificate is here:

![UC-6A6O2NT7](https://user-images.githubusercontent.com/26466644/66271723-c53b9980-e861-11e9-92c8-1d86b4ed232c.jpg)

To do so, I have to add the image of the certificate to the `client/src/images/certifications` folder with the corresponding name (do not forget to resize the image, the resolution should be the same for all the images - if I remember correctly it is 600 × 448) and register it in the `client/src/images/index.js` file.

Then in the `client/src/components/Pages/Education/constants.js` you have to add the info about the course to the `certificates` array:

![image](https://user-images.githubusercontent.com/26466644/66271706-7e4da400-e861-11e9-9f39-18e04522c4ae.png)

To work on this issue, please use a branch **DEV-38** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**IMPORTANT!** Before creating a PR be sure that all the tests are passing and the coverage is 100%.

**Comment by KovDimaY** [comment]
I have merged the PR! Great job! Thank you for your contribution, @TetianaKlymchuk! :)

**Comment by TetianaKlymchuk** [comment]
You are welcome, Dima! Happy to help!
