### ISSUE TITLE
DEV-39: Change hover effect for certifications items

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/MERN-ChatBot#67]
At the moment, the hover effect of certifications is just zooming:

![certif](https://user-images.githubusercontent.com/26466644/66554101-9f0d4680-eb4c-11e9-9f63-1b958bd43247.gif)

I want to put the same effect as I use for the 404 page:

![404d](https://user-images.githubusercontent.com/26466644/66514590-bf51ec80-eadd-11e9-9ae5-f900fa1193dd.gif)

As all the infrastructure is already prepared, it should not be very difficult to do, just to wrap the image with the tilt component.

To work on this issue, please use a branch **DEV-39** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**IMPORTANT!** Before creating a PR be sure that all the tests are passing and the coverage is 100%. Also, do not forget to update documentation both in Storybook and Styleguidist.

**Comment by gaurav219** [comment]
I'll give this a go, if it's alright!!!

**Comment by KovDimaY** [comment]
Hi, @gaurav219! Thank you for your proposal and for your interest in my project!
Yes, you can give it a try, but please, follow carefully all the rules and conventions of the project! 🙏 

Let me know if you have any questions or if you need any help with it. I will try my best helping you on the way.

Whenever you start working on it, please, put the yellow label "In Progress" to this issue and move it to "In Progress" column in the Kanban board of the General Improvements project. In case of any question, do not hesitate to write a comment on this issue.

**Comment by gaurav219** [comment]
Thank You, I can't find the file which lists the Certifications.

**Comment by amreshk005** [comment]
@KovDimaY if no one is working on it. can take this issue?

**Comment by KovDimaY** [comment]
@gaurav219, look at the `client/src/components/Pages/Education/index.js` file :)

Ah, ok, so I will do the labels stuff myself, cannot find how to give you the permissions... 🤔

**Comment by KovDimaY** [comment]
Sorry, @amreshk005, I think that @gaurav219 is already working on it.
Right, @gaurav219?

**Comment by gaurav219** [comment]
Yeah, I'm looking forward to it.

**Comment by gaurav219** [comment]
I apologize, but I think I'm unable to resolve the issue.

**Comment by KovDimaY** [comment]
No worries, @gaurav219! It is ok! Thanks for trying! 💪

**Comment by gaurav219** [comment]
Thank You for assigning me this!!
Probably will contribute in the near future.

**Comment by KovDimaY** [comment]
Sure thing, @gaurav219! You are welcome! Good luck with Hacktoberfest! 💪 

@amreshk005 do you still want to take this one?

**Comment by KovDimaY** [comment]
Finally, the effect looks like this:

![certifs](https://user-images.githubusercontent.com/26466644/66756411-3f8b9f80-ee9a-11e9-95bf-4e2249f4628d.gif)

I am creating a PR...

**Comment by KovDimaY** [comment]
The PR is merged. The issue can be closed now
