### ISSUE TITLE
DEV-43: Add and apply prettier to the project

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/MERN-ChatBot#79]
At the moment, the code is controlled by linter and it makes it quite nice and clean. But much better and useful is to have prettier installed as well and configure your editor to prettify your code automatically on save.

You can find more about prettier here: https://prettier.io/

Once prettier is installed, would be good to check all the existing files and apply prettier to all of them so the code becomes more structured and clean.

To work on this issue, please use a branch **DEV-43** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**Comment by AbhinavReddy-Dev** [comment]
Hey, I have prettier in my VS code, shall I fix this?

**Comment by KovDimaY** [comment]
Sorry, @AbhinavReddy-Dev, the PR for this issue is already merged.
